version: "3.5"

services:
  demo-symfony6-web:
    container_name: demo-symfony6-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "250:80"
    volumes:
      # punto de entrada de la app symfony
      - ./public:/appdata/www/
    depends_on:
      - demo-symfony6-be
    networks:
      - demo-symfony6-network

  demo-symfony6-be:
    env_file:
      - ./docker/proxy.env
    container_name: demo-symfony6-be
    build:
      # Proxy configurado en el Dockerfile, no toma los archivos .env en el build
      context: docker/php
      args:
        UID: $U_ID
    environment:
      ###> XDEBUG 3 ###
      # Use your client IP here
      # Linux: run "ip a | grep docker0"
      # Windows (with WSL2) and Mac: host.docker.internal
      # Las configuraciones se reflejan el archivo docker/php/xdebug.ini
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9005
      XDEBUG_ID_KEY: PHPSTORM
      PHP_IDE_CONFIG: serverName=Docker
      DEBUG: 1
    working_dir: /appdata/www
    volumes:
      - ./:/appdata/www
      - ../00_Bundles/maker-bundle:/appdata/00_Bundles/maker-bundle
      - ./docker/php/php.ini:$PHP_INI_DIR/php.ini
      - ./docker/php/xdebug.ini:$PHP_INI_DIR/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - demo-symfony6-db
    networks:
      - demo-symfony6-network

  demo-symfony6-db:
    container_name: demo-symfony6-db
    build:
      context: ./docker/database
    ports:
      - "36001:3306"
    environment:
      MYSQL_DATABASE: "mprod_demo8"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - demo-symfony6-db-data:/var/lib/mysql
      - "./docker/database/mysqld.cnf:/etc/mysql/mysqld.cnf"
    networks:
      - demo-symfony6-network

  demo8-phpmyadmin:
    container_name: demo-symfony6-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: demo-symfony6-db
    depends_on:
      - demo-symfony6-db
    networks:
      - demo-symfony6-network

  demo8-portainer:
    image: portainer/portainer-ce:latest
    container_name: demo8-portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9000:9000"
    networks:
      - demo-symfony6-network

volumes:
  demo-symfony6-db-data:

networks:
  demo-symfony6-network:
    external: true
