<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEzsjlUg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEzsjlUg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEzsjlUg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEzsjlUg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEzsjlUg\App_KernelDevDebugContainer([
    'container.build_hash' => 'EzsjlUg',
    'container.build_id' => 'ec60fc61',
    'container.build_time' => 1661887412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEzsjlUg');
